[development]
address = "localhost"
port = 8000
keep_alive = 5
log = "normal"
dir_name = "./"

[staging]
address = "0.0.0.0"
port = 80
keep_alive = 5
log = "normal"
dir_name = "./"

[production]
address = "0.0.0.0"
port = 80
keep_alive = 5
log = "critical"
dir_name = "./"
